name: colorsdj
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase e Google/Facebook:
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  # flutter_facebook_login: ^3.0.0  
  firebase_storage: ^3.1.6
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16

  #imagens, sons e fonts:
  image: ^2.1.12
  image_picker: ^0.6.7+4
  animator: ^2.0.1
  google_fonts: ^1.1.0
  material_design_icons_flutter: ^4.0.5345
  curved_navigation_bar: ^0.3.3
  flip_card: ^0.4.4
  animations: ^1.1.2
  video_player: ^0.10.11+2
  file_picker: ^1.13.3
  music_player: ^0.1.5
  flutter_svg:


  #outros:
  geolocator: ^5.3.2+2
  uuid: ^2.2.0
  path_provider: ^1.6.11
  timeago: ^2.0.26
  cached_network_image: ^2.2.0+1
  flutter_modular: ^1.3.1
  device_info: ^0.4.2+4
  sqflite: ^1.3.1
  random_string: ^2.1.0
  path: ^1.7.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/facebooklogin.png
    - assets/images/google_signin_button.png
    - assets/images/Logomarca_Colors.png
    - assets/images/Logomarca_Colors.svg
    - assets/images/Logotipo_Colors.svg
    - assets/images/Manual_Marca_Logotipo_Colors.png
    - assets/images/Marca_Logomarca_Colors.png
    - assets/images/no_content.svg
    - assets/images/search.svg
    - assets/images/upload.svg 



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
